/**
 * Document Agent — create_excel, create_pdf, generate_project_report,
 * create_mom, save_report_template, list_report_templates tools.
 *
 * The AI calls these tools with structured data and gets back a download link.
 * This gives ARIA full control over document content and design.
 */
import fs from 'fs';
import path from 'path';
import ExcelJS from 'exceljs';
import { createClient } from '@supabase/supabase-js';
import type { BridgeAdapter } from '@aria/core';
import { reportRegistry } from '../routes/download.js';

function db() {
  return createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_ANON_KEY!,
  );
}

function fmtDate(d: Date) {
  return d.toLocaleString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

const OUT_DIR = '/tmp/aria-generated';
fs.mkdirSync(OUT_DIR, { recursive: true });

// ─── Palette ──────────────────────────────────────────────────────────────────

const P = {
  darkBg:    'FF1C1A15',
  headerBg:  'FF2B2926',
  accent:    'FF7C6AF4',
  accentSoft:'FFF0EDFE',
  green:     'FF3A9E6E',
  greenSoft: 'FFE6F5EE',
  red:       'FFB53333',
  redSoft:   'FFFDEAEA',
  orange:    'FFC96442',
  orangeSoft:'FFFEF0EA',
  white:     'FFFFFFFF',
  offWhite:  'FFFAF8F3',
  altRow:    'FFF5F3EE',
  border:    'FFE5E1D6',
  text:      'FF1C1A15',
  textMid:   'FF5A5750',
  textLight: 'FF9A9890',
};

function statusColor(status: string): { fg: string; bg: string } {
  const s = status.toLowerCase();
  if (s.includes('done') || s.includes('complet')) return { fg: P.green,  bg: P.greenSoft };
  if (s.includes('overdue') || s.includes('late'))  return { fg: P.red,   bg: P.redSoft };
  if (s.includes('progress') || s.includes('active')) return { fg: P.accent, bg: P.accentSoft };
  return { fg: P.textMid, bg: P.offWhite };
}

function priorityColor(priority: string): string {
  const p = priority.toLowerCase();
  if (p === 'critical' || p === 'urgent') return P.red;
  if (p === 'high')   return P.orange;
  if (p === 'low')    return P.textLight;
  return P.textMid;
}

// ─── Excel generator ──────────────────────────────────────────────────────────

interface ExcelSheet {
  name: string;
  headers: string[];
  rows: (string | number)[][];
  summaryRow?: string[];
  statusCol?: number;
  priorityCol?: number;
}

interface ExcelInput {
  title: string;
  subtitle?: string;
  sheets: ExcelSheet[];
  generated_at?: string;
}

async function buildExcel(input: ExcelInput): Promise<string> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'ARIA';
  wb.created = new Date();

  const genAt = input.generated_at ?? new Date().toLocaleString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  // ── Cover sheet ──────────────────────────────────────────────────────────────
  const cover = wb.addWorksheet('Cover');
  cover.views = [{ showGridLines: false }];
  cover.getColumn('A').width = 60;

  // Title block
  const titleRow = cover.addRow([input.title]);
  titleRow.height = 42;
  const titleCell = titleRow.getCell(1);
  titleCell.font   = { size: 22, bold: true, color: { argb: P.text }, name: 'Calibri' };
  titleCell.fill   = { type: 'pattern', pattern: 'solid', fgColor: { argb: P.accentSoft } };
  titleCell.border = { left: { style: 'thick', color: { argb: P.accent } } };
  titleCell.alignment = { vertical: 'middle', indent: 2 };

  if (input.subtitle) {
    const subRow = cover.addRow([input.subtitle]);
    subRow.height = 24;
    const subCell = subRow.getCell(1);
    subCell.font      = { size: 12, color: { argb: P.textMid }, name: 'Calibri' };
    subCell.alignment = { vertical: 'middle', indent: 2 };
  }

  const metaRow = cover.addRow([`Generated by ARIA  •  ${genAt}`]);
  metaRow.getCell(1).font      = { size: 10, color: { argb: P.textLight }, italic: true };
  metaRow.getCell(1).alignment = { indent: 2 };

  cover.addRow([]);

  // Sheet index
  const idxHeader = cover.addRow(['Sheets in this workbook']);
  idxHeader.getCell(1).font = { size: 11, bold: true, color: { argb: P.text } };
  idxHeader.getCell(1).alignment = { indent: 2 };
  input.sheets.forEach((s, i) => {
    const r = cover.addRow([`  ${i + 1}.  ${s.name}  (${s.rows.length} rows)`]);
    r.getCell(1).font = { size: 10, color: { argb: P.textMid } };
  });

  // ── Data sheets ──────────────────────────────────────────────────────────────
  for (const sheet of input.sheets) {
    const ws = wb.addWorksheet(sheet.name.slice(0, 31));
    ws.views = [{ state: 'frozen', ySplit: 1, showGridLines: false }];

    // Set columns
    ws.columns = sheet.headers.map((h, i) => ({
      key: `c${i}`,
      width: i === 0 ? 40 : Math.max(14, h.length + 4),
      header: h,
    }));

    // Header row styling
    const hRow = ws.getRow(1);
    hRow.height = 28;
    sheet.headers.forEach((h, i) => {
      const cell = hRow.getCell(i + 1);
      cell.value = h;
      cell.font  = { bold: true, color: { argb: P.white }, size: 10, name: 'Calibri' };
      cell.fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: P.headerBg } };
      cell.border = {
        bottom: { style: 'medium', color: { argb: P.accent } },
        right:  i < sheet.headers.length - 1 ? { style: 'thin', color: { argb: 'FF3A3836' } } : undefined,
      };
      cell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 };
    });

    // Auto-filter
    if (sheet.rows.length > 0) {
      ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: sheet.headers.length } };
    }

    // Data rows
    sheet.rows.forEach((row, rowIdx) => {
      const dataRow = ws.addRow(row);
      dataRow.height = 22;
      const isAlt = rowIdx % 2 === 1;

      row.forEach((_cell, colIdx) => {
        const cell = dataRow.getCell(colIdx + 1);
        const raw  = String(row[colIdx] ?? '');

        // Default fill
        cell.fill = {
          type: 'pattern', pattern: 'solid',
          fgColor: { argb: isAlt ? P.altRow : P.offWhite },
        };
        cell.font      = { size: 10, color: { argb: P.textMid }, name: 'Calibri' };
        cell.alignment = { vertical: 'middle', indent: 1, wrapText: false };
        cell.border    = {
          bottom: { style: 'thin', color: { argb: P.border } },
        };

        // Status column highlighting
        if (sheet.statusCol !== undefined && colIdx === sheet.statusCol && raw) {
          const { fg, bg } = statusColor(raw);
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } };
          cell.font = { size: 9, bold: true, color: { argb: fg }, name: 'Calibri' };
          cell.alignment = { vertical: 'middle', horizontal: 'center' };
        }

        // Priority column highlighting
        if (sheet.priorityCol !== undefined && colIdx === sheet.priorityCol && raw) {
          cell.font = { size: 9, bold: true, color: { argb: priorityColor(raw) }, name: 'Calibri' };
        }
      });
    });

    // Summary row
    if (sheet.summaryRow) {
      ws.addRow([]);
      const sumRow = ws.addRow(sheet.summaryRow);
      sumRow.height = 24;
      sumRow.eachCell((cell, col) => {
        if (sheet.summaryRow![col - 1]) {
          cell.font  = { bold: true, size: 10, color: { argb: P.text }, name: 'Calibri' };
          cell.fill  = { type: 'pattern', pattern: 'solid', fgColor: { argb: P.accentSoft } };
          cell.alignment = { vertical: 'middle', indent: 1 };
          cell.border = { top: { style: 'medium', color: { argb: P.accent } } };
        }
      });
    }
  }

  const fileId   = crypto.randomUUID();
  const fileName = `ARIA_${input.title.replace(/[^a-z0-9]/gi, '_').slice(0, 40)}_${Date.now()}.xlsx`;
  const filePath = path.join(OUT_DIR, `${fileId}.xlsx`);

  await wb.xlsx.writeFile(filePath);
  const size = fs.statSync(filePath).size;

  reportRegistry.set(fileId, { fileId, fileName, filePath, type: 'xlsx', size, createdAt: new Date().toISOString() });
  return JSON.stringify({
    fileId,
    fileName,
    type: 'xlsx',
    size,
    url: `/api/aria/download/${fileId}`,
    message: `Excel file created: ${fileName} (${Math.round(size / 1024)}KB, ${input.sheets.length} sheet${input.sheets.length > 1 ? 's' : ''})`,
  });
}

// ─── PDF generator ────────────────────────────────────────────────────────────

interface PdfStat  { label: string; value: string; color?: string }
interface PdfList  { type: 'list';  heading: string; items: string[] }
interface PdfText  { type: 'text';  heading?: string; content: string }
interface PdfTable { type: 'table'; heading?: string; headers: string[]; rows: string[][] }
interface PdfStats { type: 'stats'; items: PdfStat[] }

type PdfSection = PdfList | PdfText | PdfTable | PdfStats;

interface PdfInput {
  title: string;
  subtitle?: string;
  sections: PdfSection[];
  generated_at?: string;
}

async function buildPDF(input: PdfInput): Promise<string> {
  const PDFMod = await import('pdfkit');
  const PDFDocument = (PDFMod as any).default ?? PDFMod;

  const fileId   = crypto.randomUUID();
  const fileName = `ARIA_${input.title.replace(/[^a-z0-9]/gi, '_').slice(0, 40)}_${Date.now()}.pdf`;
  const filePath = path.join(OUT_DIR, `${fileId}.pdf`);

  const genAt = input.generated_at ?? new Date().toLocaleString('en-GB', {
    day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });

  await new Promise<void>((resolve, reject) => {
    const doc    = new PDFDocument({ margin: 56, size: 'A4', bufferPages: true });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    stream.on('finish', resolve);
    stream.on('error', reject);

    const W     = doc.page.width;
    const LEFT  = 56;
    const RIGHT = W - 56;
    const INNER = RIGHT - LEFT;

    // ── Cover header band ──────────────────────────────────────────────────────
    doc.rect(0, 0, W, 10).fill('#7c6af4');   // thin top accent bar
    doc.rect(0, 10, W, 130).fill('#1c1a15'); // dark title band

    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(28)
       .text('ARIA', LEFT, 38, { continued: false });

    doc.font('Helvetica').fontSize(9).fillColor('#9a9890')
       .text('Intelligent Reports', LEFT, 70);

    doc.rect(LEFT, 82, 32, 2).fill('#7c6af4');

    const titleY = input.subtitle ? 100 : 108;
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(18)
       .text(input.title, LEFT, titleY, { width: INNER - 60 });

    if (input.subtitle) {
      doc.font('Helvetica').fontSize(10).fillColor('#9a9890')
         .text(input.subtitle.slice(0, 90), LEFT, 122, { width: INNER - 60 });
    }

    doc.font('Helvetica').fontSize(8).fillColor('#5a5750')
       .text(genAt, RIGHT - 120, 128, { width: 120, align: 'right' });

    doc.y = 160;

    // ── Section renderer ───────────────────────────────────────────────────────
    function sectionHeading(text: string) {
      if (doc.y > doc.page.height - 140) doc.addPage();
      const y = doc.y;
      doc.rect(LEFT, y, 3, 18).fill('#7c6af4');
      doc.fillColor('#1c1a15').font('Helvetica-Bold').fontSize(13)
         .text(text, LEFT + 10, y + 2, { width: INNER - 10 });
      doc.y = y + 26;
    }

    function renderStats(items: PdfStat[]) {
      const cols = Math.min(items.length, 4);
      const boxW = (INNER - (cols - 1) * 10) / cols;
      const startY = doc.y;

      items.slice(0, 4).forEach((item, i) => {
        const x = LEFT + i * (boxW + 10);
        doc.rect(x, startY, boxW, 56).fill('#f5f3ee');
        doc.rect(x, startY, boxW, 3).fill(item.color ?? '#7c6af4');

        doc.fillColor('#1c1a15').font('Helvetica-Bold').fontSize(22)
           .text(item.value, x, startY + 10, { width: boxW, align: 'center' });
        doc.font('Helvetica').fontSize(9).fillColor('#5a5750')
           .text(item.label, x, startY + 38, { width: boxW, align: 'center' });
      });

      doc.y = startY + 70;
    }

    function renderText(section: PdfText) {
      if (section.heading) sectionHeading(section.heading);
      if (doc.y > doc.page.height - 100) doc.addPage();
      doc.font('Helvetica').fontSize(10.5).fillColor('#5a5750')
         .text(section.content, LEFT, doc.y, { width: INNER, lineGap: 3 });
      doc.y += 16;
    }

    function renderList(section: PdfList) {
      sectionHeading(section.heading);
      section.items.forEach(item => {
        if (doc.y > doc.page.height - 80) doc.addPage();
        const bulletY = doc.y;
        doc.circle(LEFT + 4, bulletY + 6, 3).fill('#7c6af4');
        doc.font('Helvetica').fontSize(10.5).fillColor('#5a5750')
           .text(item, LEFT + 14, bulletY, { width: INNER - 14, lineGap: 2 });
        doc.y += 4;
      });
      doc.y += 8;
    }

    function renderTable(section: PdfTable) {
      if (section.heading) sectionHeading(section.heading);
      if (section.rows.length === 0) return;

      const colW = INNER / section.headers.length;
      const ROW_H = 20;
      let ty = doc.y;

      // Header
      doc.rect(LEFT, ty, INNER, ROW_H).fill('#2b2926');
      section.headers.forEach((h, i) => {
        doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#ffffff')
           .text(h.toUpperCase(), LEFT + i * colW + 6, ty + 6, { width: colW - 12 });
      });
      ty += ROW_H;

      // Rows
      section.rows.forEach((row, ri) => {
        if (ty + ROW_H > doc.page.height - 60) {
          doc.addPage();
          ty = 60;
          // Repeat header on new page
          doc.rect(LEFT, ty, INNER, ROW_H).fill('#2b2926');
          section.headers.forEach((h, i) => {
            doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#ffffff')
               .text(h.toUpperCase(), LEFT + i * colW + 6, ty + 6, { width: colW - 12 });
          });
          ty += ROW_H;
        }

        const bg = ri % 2 === 0 ? '#faf8f3' : '#ffffff';
        doc.rect(LEFT, ty, INNER, ROW_H).fill(bg);

        row.forEach((cell, i) => {
          let color = '#5a5750';
          const cellLow = String(cell).toLowerCase();
          if (cellLow.includes('done') || cellLow.includes('complet')) color = '#3a9e6e';
          else if (cellLow.includes('overdue') || cellLow.includes('late')) color = '#b53333';
          else if (cellLow.includes('critical') || cellLow.includes('urgent')) color = '#b53333';
          else if (cellLow.includes('high')) color = '#c96442';

          doc.font('Helvetica').fontSize(8.5).fillColor(color)
             .text(String(cell).slice(0, 35), LEFT + i * colW + 6, ty + 6, { width: colW - 12 });
        });

        // Bottom border
        doc.moveTo(LEFT, ty + ROW_H).lineTo(RIGHT, ty + ROW_H)
           .lineWidth(0.3).stroke('#e5e1d6');
        ty += ROW_H;
      });

      doc.y = ty + 16;
    }

    // ── Render all sections ────────────────────────────────────────────────────
    for (const section of input.sections) {
      if (doc.y > doc.page.height - 100) doc.addPage();

      if (section.type === 'stats') {
        renderStats(section.items);
      } else if (section.type === 'text') {
        renderText(section);
      } else if (section.type === 'list') {
        renderList(section);
      } else if (section.type === 'table') {
        renderTable(section);
      }
    }

    // ── Footer on every page ───────────────────────────────────────────────────
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i);
      doc.rect(0, doc.page.height - 28, W, 28).fill('#1c1a15');
      doc.font('Helvetica').fontSize(7.5).fillColor('#5a5750')
         .text(
           `ARIA Intelligence Report  •  ${genAt}  •  Page ${i + 1} of ${range.count}`,
           LEFT, doc.page.height - 18,
           { width: INNER, align: 'center' },
         );
    }

    doc.end();
  });

  const size = fs.statSync(filePath).size;
  reportRegistry.set(fileId, { fileId, fileName, filePath, type: 'pdf', size, createdAt: new Date().toISOString() });

  return JSON.stringify({
    fileId,
    fileName,
    type: 'pdf',
    size,
    url: `/api/aria/download/${fileId}`,
    message: `PDF report created: ${fileName} (${Math.round(size / 1024)}KB, ${input.sections.length} sections)`,
  });
}

// ─── Adapters ─────────────────────────────────────────────────────────────────

export function buildDocumentAdapters(): BridgeAdapter[] {
  return [
    {
      name: 'create_excel',
      description:
        'Create a professionally styled Excel spreadsheet (.xlsx) with colored headers, ' +
        'alternating rows, status color coding (green=done, red=overdue, purple=in-progress), ' +
        'priority highlighting, frozen header row, and auto-filter. ' +
        'Call when user wants an Excel file, spreadsheet, or data export. ' +
        'You provide the structured data; ARIA handles the design. ' +
        'Returns a download link.',
      inputSchema: {
        type: 'object',
        properties: {
          title:        { type: 'string', description: 'Document title (shown on cover sheet)' },
          subtitle:     { type: 'string', description: 'Optional subtitle or description' },
          generated_at: { type: 'string', description: 'Optional date string override' },
          sheets: {
            type: 'array',
            description: 'One or more sheets of data',
            items: {
              type: 'object',
              properties: {
                name:        { type: 'string', description: 'Sheet tab name' },
                headers:     { type: 'array', items: { type: 'string' }, description: 'Column headers' },
                rows: {
                  type: 'array',
                  items: { type: 'array', items: { type: 'string' } },
                  description: 'Data rows — each row is an array of cell values matching the headers',
                },
                summaryRow:  { type: 'array', items: { type: 'string' }, description: 'Optional totals/summary row at the bottom' },
                statusCol:   { type: 'number', description: '0-based index of the status column (for color coding)' },
                priorityCol: { type: 'number', description: '0-based index of the priority column (for color coding)' },
              },
              required: ['name', 'headers', 'rows'],
            },
          },
        },
        required: ['title', 'sheets'],
      },
      async call(input) {
        const result = await buildExcel(input as unknown as ExcelInput);
        const parsed = JSON.parse(result);
        return `${parsed.message}\n\nDownload: ${parsed.url}`;
      },
    },

    {
      name: 'create_pdf',
      description:
        'Create a professionally designed PDF report with a dark header banner, ' +
        'stat cards, color-coded tables (green=done, red=overdue), bullet lists, ' +
        'and paginated text sections. ' +
        'Call when user wants a PDF report, summary, or exported document. ' +
        'You provide the structured content; ARIA handles the design and layout. ' +
        'Returns a download link.',
      inputSchema: {
        type: 'object',
        properties: {
          title:        { type: 'string', description: 'Report title' },
          subtitle:     { type: 'string', description: 'Optional subtitle' },
          generated_at: { type: 'string', description: 'Optional date/time string' },
          sections: {
            type: 'array',
            description: 'Ordered list of content sections',
            items: {
              type: 'object',
              properties: {
                type: {
                  type: 'string',
                  enum: ['stats', 'text', 'list', 'table'],
                  description:
                    'stats = metric cards (up to 4); ' +
                    'text = paragraph with optional heading; ' +
                    'list = bulleted list with heading; ' +
                    'table = data grid with header row',
                },
                heading:  { type: 'string', description: 'Section heading (for text/list/table types)' },
                content:  { type: 'string', description: 'Paragraph text (for text type)' },
                items: {
                  type: 'array', items: { oneOf: [
                    { type: 'string' },
                    { type: 'object', properties: {
                        label: { type: 'string' }, value: { type: 'string' }, color: { type: 'string' },
                      }},
                  ]},
                  description: 'Bullet items (for list type) or stat objects { label, value, color? } (for stats type)',
                },
                headers:  { type: 'array', items: { type: 'string' }, description: 'Column headers (for table type)' },
                rows: {
                  type: 'array', items: { type: 'array', items: { type: 'string' } },
                  description: 'Data rows (for table type)',
                },
              },
              required: ['type'],
            },
          },
        },
        required: ['title', 'sections'],
      },
      async call(input) {
        const result = await buildPDF(input as unknown as PdfInput);
        const parsed = JSON.parse(result);
        return `${parsed.message}\n\nDownload: ${parsed.url}`;
      },
    },

    // ── generate_project_report ──────────────────────────────────────────────
    {
      name: 'generate_project_report',
      description:
        'Fetch real project + task data from the database and generate a professional PDF ' +
        'report with stats, task table, milestones, and your AI summary. ' +
        'Use when user asks for a project report, status update, or PDF about a specific project. ' +
        'This tool queries Supabase automatically — you just provide the project name and a summary.',
      inputSchema: {
        type: 'object',
        properties: {
          user_id:      { type: 'string' },
          project_name: { type: 'string', description: 'Name or partial name of the project' },
          summary:      { type: 'string', description: 'Your 2-4 sentence executive summary of the project status' },
          period:       { type: 'string', description: 'Optional period label e.g. "May 2026" or "Q2 2026"' },
        },
        required: ['user_id', 'project_name', 'summary'],
      },
      async call(input) {
        const { user_id, project_name, summary, period } = input as {
          user_id: string; project_name: string; summary: string; period?: string;
        };

        const sb = db();
        const now = new Date();

        // Find the project
        const { data: projects } = await sb
          .from('aria_projects')
          .select('*')
          .eq('user_id', user_id)
          .ilike('name', `%${project_name}%`)
          .limit(1);

        const project = projects?.[0];
        const projId  = project?.id;
        const title   = project?.name ?? project_name;
        const goal    = project?.goal ?? project?.description ?? '';

        // Fetch tasks
        const taskQuery = sb.from('aria_tasks').select('*').eq('user_id', user_id);
        if (projId) taskQuery.eq('project_id', projId);
        const { data: rawTasks } = await taskQuery.limit(100);
        const tasks: any[] = rawTasks ?? [];

        const total    = tasks.length;
        const done     = tasks.filter((t: any) => t.status === 'completed').length;
        const active   = tasks.filter((t: any) => t.status === 'in_progress').length;
        const overdue  = tasks.filter((t: any) =>
          t.due_date && new Date(t.due_date) < now && t.status !== 'completed'
        ).length;
        const donePct  = total > 0 ? Math.round((done / total) * 100) : 0;

        const sections: PdfSection[] = [
          {
            type: 'stats',
            items: [
              { label: 'Total Tasks',  value: String(total) },
              { label: `Done (${donePct}%)`, value: String(done),   color: 'FF3A9E6E' },
              { label: 'In Progress',  value: String(active),        color: 'FF7C6AF4' },
              { label: 'Overdue',      value: String(overdue),       color: overdue > 0 ? 'FFB53333' : 'FF3A9E6E' },
            ],
          },
          { type: 'text', heading: 'Executive Summary', content: summary },
        ];

        if (tasks.length > 0) {
          sections.push({
            type: 'table',
            heading: 'Task Overview',
            headers: ['Task', 'Status', 'Priority', 'Due Date'],
            rows: tasks.slice(0, 30).map((t: any) => [
              t.title ?? '',
              (t.status ?? 'pending').replace(/_/g, ' '),
              t.priority ?? 'medium',
              t.due_date ? new Date(t.due_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : '—',
            ]),
          });
        }

        const completedRecent = tasks
          .filter((t: any) => t.status === 'completed' && t.completed_at)
          .sort((a: any, b: any) => new Date(b.completed_at).getTime() - new Date(a.completed_at).getTime())
          .slice(0, 8)
          .map((t: any) => t.title);

        if (completedRecent.length > 0) {
          sections.push({ type: 'list', heading: 'Recently Completed', items: completedRecent });
        }

        const upcoming = tasks
          .filter((t: any) => t.status !== 'completed' && t.due_date)
          .sort((a: any, b: any) => new Date(a.due_date).getTime() - new Date(b.due_date).getTime())
          .slice(0, 6)
          .map((t: any) => `${t.title} — due ${new Date(t.due_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}`);

        if (upcoming.length > 0) {
          sections.push({ type: 'list', heading: 'Upcoming Deadlines', items: upcoming });
        }

        const pdfInput: PdfInput = {
          title: `${title}${period ? ` — ${period}` : ''}`,
          subtitle: goal || undefined,
          sections,
          generated_at: fmtDate(now),
        };

        const result = await buildPDF(pdfInput);
        const parsed = JSON.parse(result);
        return `Project report for "${title}" generated.\n${parsed.message}\n\nDownload: ${parsed.url}`;
      },
    },

    // ── create_mom ───────────────────────────────────────────────────────────
    {
      name: 'create_mom',
      description:
        'Create a professional Minutes of Meeting (MOM) PDF document. ' +
        'Call when user wants to document a meeting, record meeting notes, or create MOM/meeting minutes.',
      inputSchema: {
        type: 'object',
        properties: {
          title:        { type: 'string', description: 'Meeting title or project name' },
          date:         { type: 'string', description: 'Meeting date and time' },
          location:     { type: 'string', description: 'Meeting location or platform (e.g. Zoom, Office)' },
          chair:        { type: 'string', description: 'Meeting chairperson/facilitator' },
          attendees:    { type: 'array', items: { type: 'string' }, description: 'List of attendees (name + role)' },
          agenda:       { type: 'array', items: { type: 'string' }, description: 'Agenda items discussed' },
          discussion:   { type: 'array', items: { type: 'string' }, description: 'Key discussion points and notes' },
          decisions:    { type: 'array', items: { type: 'string' }, description: 'Decisions made in the meeting' },
          action_items: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                item:  { type: 'string' },
                owner: { type: 'string' },
                due:   { type: 'string' },
              },
            },
            description: 'Action items with owner and due date',
          },
          next_meeting: { type: 'string', description: 'Next meeting date/time (optional)' },
        },
        required: ['title', 'date', 'attendees'],
      },
      async call(input) {
        const {
          title, date, location, chair, attendees = [],
          agenda = [], discussion = [], decisions = [],
          action_items = [], next_meeting,
        } = input as {
          title: string; date: string; location?: string; chair?: string;
          attendees: string[]; agenda: string[]; discussion: string[];
          decisions: string[]; action_items: Array<{ item: string; owner: string; due: string }>;
          next_meeting?: string;
        };

        const sections: PdfSection[] = [];

        // Meeting meta as a text block
        const meta = [
          `Date: ${date}`,
          location ? `Location: ${location}` : '',
          chair    ? `Chaired by: ${chair}` : '',
        ].filter(Boolean).join('\n');

        sections.push({ type: 'text', heading: 'Meeting Details', content: meta });
        sections.push({ type: 'list', heading: 'Attendees', items: attendees });

        if (agenda.length > 0) {
          sections.push({ type: 'list', heading: 'Agenda', items: agenda });
        }
        if (discussion.length > 0) {
          sections.push({ type: 'list', heading: 'Discussion Points', items: discussion });
        }
        if (decisions.length > 0) {
          sections.push({ type: 'list', heading: 'Decisions Made', items: decisions });
        }
        if (action_items.length > 0) {
          sections.push({
            type: 'table',
            heading: 'Action Items',
            headers: ['Action Item', 'Owner', 'Due Date'],
            rows: action_items.map(a => [a.item, a.owner || '—', a.due || '—']),
          });
        }
        if (next_meeting) {
          sections.push({ type: 'text', heading: 'Next Meeting', content: next_meeting });
        }

        const pdfInput: PdfInput = {
          title: `Minutes of Meeting — ${title}`,
          subtitle: date,
          sections,
          generated_at: fmtDate(new Date()),
        };

        const result = await buildPDF(pdfInput);
        const parsed = JSON.parse(result);
        return `MOM document created.\n${parsed.message}\n\nDownload: ${parsed.url}`;
      },
    },

    // ── save_report_template ──────────────────────────────────────────────────
    {
      name: 'save_report_template',
      description:
        'Save a report template so ARIA can recreate it on demand. ' +
        'Use when user says "remember this format", "save this as my monthly report template", ' +
        '"learn my MOM format", or "use this structure next time". ' +
        'The template captures what sections, headings, and structure the user wants.',
      inputSchema: {
        type: 'object',
        properties: {
          user_id:     { type: 'string' },
          name:        { type: 'string', description: 'Template name e.g. "Monthly Report", "Minutes of Meeting"' },
          description: { type: 'string', description: 'What this template is for' },
          sections: {
            type: 'array',
            description: 'Ordered list of section specs the user wants',
            items: {
              type: 'object',
              properties: {
                heading: { type: 'string' },
                type:    { type: 'string', enum: ['stats', 'text', 'list', 'table'] },
                notes:   { type: 'string', description: 'What content goes here' },
              },
            },
          },
          sample:      { type: 'string', description: 'User-provided sample text/description of the format' },
        },
        required: ['user_id', 'name', 'sections'],
      },
      async call(input) {
        const { user_id, name, description, sections, sample } = input as {
          user_id: string; name: string; description?: string;
          sections: Array<{ heading?: string; type: string; notes?: string }>;
          sample?: string;
        };

        const { error } = await db()
          .from('aria_report_templates')
          .upsert({
            user_id,
            name,
            description,
            template_json: { sections },
            sample,
            updated_at: new Date().toISOString(),
          }, { onConflict: 'user_id,name' });

        if (error) throw new Error(error.message);
        return `Template "${name}" saved. I'll use this format whenever you ask for a ${name}.`;
      },
    },

    // ── list_report_templates ─────────────────────────────────────────────────
    {
      name: 'list_report_templates',
      description:
        'List saved report templates for this user. ' +
        'Use when user asks "what report formats do I have", "show my templates", ' +
        'or before generating a report to check if there is a saved format to follow.',
      inputSchema: {
        type: 'object',
        properties: { user_id: { type: 'string' } },
        required: ['user_id'],
      },
      async call(input) {
        const { user_id } = input as { user_id: string };
        const { data, error } = await db()
          .from('aria_report_templates')
          .select('name, description, created_at, updated_at')
          .eq('user_id', user_id)
          .order('updated_at', { ascending: false });

        if (error) throw new Error(error.message);
        if (!data || data.length === 0) return 'No report templates saved yet.';

        return data.map((t: any) => `• ${t.name}${t.description ? ` — ${t.description}` : ''}`).join('\n');
      },
    },
  ];
}
